
question_data = [{"category": "General Knowledge",
                                      "type": "multiple",
                                      "difficulty": "easy",
                                      "question": "Where is the train station ?",
                                      "correct_answer": "Wales",
                                      "incorrect_answers": ["Moldova", "Czech Republic", "Denmark"]},
                                     {"category": "Entertainment: Television", "type": "multiple",
                                      "difficulty": "medium",
                                      "question": "Which track by Massive Attack is used for the theme of/House? ",
                                      "correct_answer": "Teardrop",
                                      "incorrect_answers": ["Protection", "Angel", "Black Milk"]},
                                     {"category": "Entertainment: Cartoon & Animations", "type": "multiple",
                                      "difficulty": "easy",
                                      "question": "What was the name of the sea witch in the 1989 Disney film The Little Mermaid ?",
                                      "correct_answer": "Ursula",
                                      "incorrect_answers": ["Madam Mim", "Maleficent", "Lady Tremaine"]},
                                     {"category": "Entertainment: Music", "type": "multiple", "difficulty": "medium",
                                      "question": "Saul Hudson (Slash) of the band Guns N&#039; Roses is known for playing what type of guitar?",
                                      "correct_answer": "Les Paul Standard",
                                      "incorrect_answers": ["Fender Stratocaster", "LsL Mongrel", "Gretsch Falcon"]},
                                     {"category": "Entertainment: Film", "type": "multiple", "difficulty": "medium",
                                      "question": "In what year was the first Transformers movie released?",
                                      "correct_answer": "1986", "incorrect_answers": ["2007", "1984", "2009"]},
                                     {"category": "General Knowledge", "type": "multiple", "difficulty": "hard",
                                      "question": "Which of the following is not another name for the eggplant?",
                                      "correct_answer": "Potimarron",
                                      "incorrect_answers": ["Brinjal", "Guinea Squash", "Melongene"]},
                                     {"category": "Entertainment: Video Games", "type": "multiple",
                                      "difficulty": "medium",
                                      "question": "In Call of Duty: United Offensive, what two soldiers share a name of a video game character?",
                                      "correct_answer": "Gordon &amp; Freeman",
                                      "incorrect_answers": ["Sam &amp; Fisher", "Nathan &amp; Drake", "Dig &amp; Dug"]},
                                     {"category": "Celebrities", "type": "multiple", "difficulty": "medium",
                                      "question": "When was Elvis Presley born?", "correct_answer": "January 8, 1935",
                                      "incorrect_answers": ["December 13, 1931", "July 18, 1940", "April 17, 1938"]},
                                     {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                                      "question": "Fast food restaurant chains Carl&#039;s Jr. and Hardee&#039;s are owned by the same company.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "History", "type": "multiple", "difficulty": "medium",
                                      "question": "What was the unofficial name for Germany between 1919 and 1933?",
                                      "correct_answer": "Weimar Republic",
                                      "incorrect_answers": ["German Democratic Republic", "Federal Republic of Germany",
                                                            "Oesterreich "]},
                                     {"category": "Entertainment: Video Games", "type": "boolean",
                                      "difficulty": "medium",
                                      "question": "Resident Evil 4 was originally meant to be a Nintendo GameCube exclusive.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "General Knowledge", "type": "multiple", "difficulty": "medium",
                                      "question": "What was the original name of the search engine &quot;Google&quot;?",
                                      "correct_answer": "BackRub",
                                      "incorrect_answers": ["CatMassage", "SearchPro", "Netscape Navigator"]},
                                     {"category": "Sports", "type": "multiple", "difficulty": "easy",
                                      "question": "When was the first official international game played?",
                                      "correct_answer": "1872", "incorrect_answers": ["1880", "1863", "1865"]},
                                     {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
                                      "question": "What is the Zodiac symbol for Gemini?", "correct_answer": "Twins",
                                      "incorrect_answers": ["Fish", "Scales", "Maiden"]},
                                     {"category": "Entertainment: Television", "type": "multiple", "difficulty": "hard",
                                      "question": "Which former Coronation Street actress was once a hostess on the British Game Show &quot;Double Your Money&quot;?",
                                      "correct_answer": "Amanda Barrie",
                                      "incorrect_answers": ["Sue Nicholls", "Violet Carson", "Jean Alexander"]},
                                     {"category": "Animals", "type": "multiple", "difficulty": "easy",
                                      "question": "What colour is the female blackbird?", "correct_answer": "Brown",
                                      "incorrect_answers": ["Black", "White", "Yellow"]},
                                     {"category": "Entertainment: Video Games", "type": "multiple",
                                      "difficulty": "medium",
                                      "question": "In Call of Duty: Modern Warfare 2, how many consecutive kills does it require to earn the &quot;Tactical Nuke&quot; killstreak?",
                                      "correct_answer": "25", "incorrect_answers": ["20", "30", "35"]},
                                     {"category": "General Knowledge", "type": "multiple", "difficulty": "hard",
                                      "question": "Which of these cities does NOT have a United States Minting location?",
                                      "correct_answer": "St. Louis, MO",
                                      "incorrect_answers": ["San Fransisco, CA", "Philidelphia, PA", "West Point, NY"]},
                                     {"category": "History", "type": "multiple", "difficulty": "medium",
                                      "question": "During which American Civil War campaign did Union troops dig a tunnel beneath Confederate troops to detonate explosives underneath them?",
                                      "correct_answer": "Siege of Petersburg",
                                      "incorrect_answers": ["Siege of Vicksburg", "Antietam Campaign",
                                                            "Gettysburg Campagin"]},
                                     {"category": "Entertainment: Music", "type": "multiple", "difficulty": "medium",
                                      "question": "In what year was Tchaikovsky&#039;s 1812 Overture composed?",
                                      "correct_answer": "1880", "incorrect_answers": ["1812", "1790", "1840"]},
                                     {"category": "Sports", "type": "multiple", "difficulty": "medium",
                                      "question": "Which country did Kabaddi, a contact sport involving tackling, originate from?",
                                      "correct_answer": "India",
                                      "incorrect_answers": ["Australia", "Turkey", "Cambodia"]}
]
